name: Ruby CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.5, 2.6, 2.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install -j2 --quiet --without=itamae
      - name: Install gem
        run: bundle exec rake install
      - name: Set up test app
        run: bundle install -j2
        working-directory: ./bizside_test_app
      - name: Run tests
        run: bundle exec rake test CONFIG_FILE=bizside_test_app/config/bizside.yml
